language: python

python:
    - "2.7"
    - "pypy"
    - "3.3"
    - "3.4"
    - "3.5"

install:
    - python setup.py --quiet install

script:
    - chmod +x test.bash
    - nosetests
    - ./test.bash
